# Clearpath settings to support ROS 2 communication of large data
# Decrease timeout for fragmented packets
net.ipv4.ipfrag_time=3
# Increase buffer to adapt for large incoming fragmented data
net.ipv4.ipfrag_high_thresh=134217728
# Increase receive buffer
net.core.rmem_max=8388608
net.core.rmem_default=8388608